services:
  sqlite-web:
    image: sqrt3/sqlite-web
    environment:
      SQLITE_DATABASE: sqlite.db
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: sqlite-data
        target: /data
        volume:
          nocopy: true

volumes:
  sqlite-data:
